### ISSUE TITLE
Linux installation

### ISSUE THREAD

**Issue by eliddell1** [vergecurrency/verge-core-installers#10]
you site links to this repo as a linux auto installer for the verge wallet.. but there are no linux install instructions only Mac and Windows

**Comment by burakim** [comment]
Can you tell me which page refer to you here for Linux installer?

**Comment by eliddell1** [comment]
the verge website under wallets>Desktop  has a link called linux auto installer that links to  https://github.com/vergecurrency/verge-core-installers

there is no mention of linux in the read me and certainly no installer in that repo..  you folks want to claim to be up and easy for grandma to use, well you should at least provide some instructions.. god, so disappointing

**Comment by burakim** [comment]
@eliddell1 You are right. I wasn't informed about Linux link, I'll add auto Linux installer to my agenda. Thank you.

**Comment by eliddell1** [comment]
also will that installer have wraith?  because this one does not have wraith: https://github.com/vergecurrency/electrum-xvg

where do i get wraith for linux!!??

**Comment by burakim** [comment]
It is in Verge Core repository. Unfortunately, lightweight electrum has not supported wraith yet.

**Comment by eliddell1** [comment]
how do i uninstall electrum-xvg wallet on linux so that my keys are not there any more?

**Comment by burakim** [comment]
You need to open issue in electrum repository. One of electrum collaborator will help you.
