### ISSUE TITLE
Wallet Synchronization problem

### ISSUE THREAD

**Issue by gokhanbulut34** [vergecurrency/verge-core-installers#6]
Gönderdiğin script i calıştırdığımda aldığım hata;

Ali-iMac:~ aliakmis$ python verge_blockchain_download.py
  File "verge_blockchain_download.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

Sierra 10.12.6 kullanıyorum. Yani High Sierra değil. Bu arada cüzdanı açmayı başarabildim. Brew doctor' u kurunca cüzdan açıldı fakat senkronize olmuyor.

Selamlar, iyi calışmalar
![ekran resmi 2018-01-03 10 57 55](https://user-images.githubusercontent.com/35061600/34514896-a705dc44-f080-11e7-8f39-3aa244d5b7ff.png)

**Comment by gokhanbulut34** [comment]
Problemin çözümünü buldum buldum Burak, benim indirdiğim dosya ile senin yazdığın script farklı. Linki kaydete basarak indirmiştim, içeriğine baktığımda senin 61 satırlık koddan çok daha fazlası vardı. Ben de 61 satırlık kodu yapıştırarak tekrar denedim, şu an indirmeye başladı.

İstanbul'dan selamlar kolay gelsin

**Comment by burakim** [comment]
@gokhanbulut34 Happy Verge Transactions!
